# Parameters for optimization routines
# Extra optimizations can be added as is done in "transfer:"

problem: hadamard

input-states:
  - '0'

state:
  opt-1:
    iters: 20
    acq: 'ucb'
    kappa: 10
    kappa-decay: 1.0
    kappa-delay: 20
    kappa-min: 0

transfer:
  opt-1:
    iters: 30
    acq: 'multi_ucb'
    kappa: 100
    kappa-decay: 0
    kappa-delay: 15
    kappa-min: 0
    alpha: 10
    alpha-decay: 0.8
    alpha-delay: 10
    alpha-min: 0
    pow: 2
  opt-2:
    iters: 160
    acq: 'ucb'
    kappa: 1
    kappa-decay: 0.8
    kappa-delay: 30

control:
  opt-1:
    iters: 200
    acq: 'ucb'
    kappa: 5
    kappa-decay: 0.8
    kappa-delay: 50
    kappa-min: 0

# Number of initialization iters for state and control optimizers
# These values must be the same for state and contorl to keep the testing fair
state-control-init: 10

transfer-init:
    iters: 5
    acq: 'ucb'
    kappa: 0.1
    xi: 0.0
    type:
      - 'state'
      # - 'random'

cost:
  state: 1
  gate: 2

pbounds:
  a1:
    !!python/tuple [-3.14, 3.14]
  a2:
    !!python/tuple [-3.14, 3.14]