# Parameters for optimization routines
# Extra optimizations can be added as is done in "transfer:"

problem: three_q_yz

input-states:
  - '+++'
  - 'RRR'

state:
  opt-1:
    iters: 30
    acq: 'ucb'
    kappa: 10
    kappa-decay: 1.0
    kappa-delay: 150

transfer:
  opt-1:
    iters: 30
    acq: 'multi_ucb'
    kappa: 100
    kappa-decay: 1.0
    kappa-delay: 30
    kappa-min: 1
    alpha: 1
    alpha-decay: 0.8
    alpha-delay: 10
    alpha-min: 0
    pow: 2
  opt-2:
    iters: 200
    acq: 'ucb'
    kappa: 0.2
    kappa-decay: 0.7
    kappa-delay: 20

control:
  opt-1:
    iters: 2
    acq: 'ucb'
    kappa: 10
    kappa-decay: 0.95
    kappa-delay: 30

# Number of initialization iters for state and control optimizers
# These values must be the same for state and contorl to keep the testing fair
state-control-init: 50

transfer-init:
    iters: 10
    acq: 'ucb'
    kappa: 0.5
    xi: 0.0
    type: 'state'

cost:
  state: 1
  gate: 8

pbounds:
  a1:
    !!python/tuple [-3.14, 3.14]
  a2:
    !!python/tuple [-3.14, 3.14]
  a3:
    !!python/tuple [-3.14, 3.14]
  a4:
    !!python/tuple [-3.14, 3.14]
  a5:
    !!python/tuple [-3.14, 3.14]
  a6:
    !!python/tuple [-3.14, 3.14]
