problem: two_q

input-states:
  - '00'


control:
  opt-1:
    iters: 200
    acq: 'ucb'
    kappa: 1
    kappa-decay: 0.96
    decay-delay: 30

# Number of initialization iters for state and control optimizers
# These values must be the same for state and contorl to keep the testing fair
state-control-init: 20

cost:
  state: 1
  gate: 4

pbounds:
  a1:
    !!python/tuple [-2, 2]
  a2:
    !!python/tuple [-2, 2]
  a3:
    !!python/tuple [-2, 2]
  a4:
    !!python/tuple [-2, 2]