# Parameters for optimization routines
# Extra optimizations can be added as is done in "transfer:"
problem: three_q

input-states:
  - '111'

state:
  opt-1:
    iters: 100
    acq: 'ucb'
    kappa: 5
    kappa-decay: 1
    kappa-delay: 0

transfer:
  opt-1:
    iters: 200
    acq: 'multi_ucb'
    kappa: 100
    kappa-decay: 1
    kappa-delay: 0

# Number of initialization iters for state and control optimizers
# These values must be the same for state and contorl to keep the testing fair
state-control-init: 30

transfer-init:
    iters: 10
    acq: 'ucb'
    kappa: 1
    xi: 0.0

cost:
  state: 1
  gate: 8

pbounds:
  a1:
    !!python/tuple [0, 2]
  a2:
    !!python/tuple [0, 2]
  a3:
    !!python/tuple [0, 2]
  a4:
    !!python/tuple [0, 2]
  a5:
    !!python/tuple [0, 2]
  a6:
    !!python/tuple [0, 2]
