iters:
  init: 20
  state-opt: 50
  control-opt: 40
  transfer-init: 5
  transfer-opt: 20
  transfer-refine: 28

cost:
  state: 1
  gate: 10

pbounds:
  a1:
    !!python/tuple [0, 2]
  a2:
    !!python/tuple [-2,2]