problem: three_q

input-states:
  - '000'


control:
  opt-1:
    iters: 200
    acq: 'ucb'
    kappa: 1
    kappa-decay: 0.98
    decay-delay: 50

# Number of initialization iters for state and control optimizers
# These values must be the same for state and contorl to keep the testing fair
state-control-init: 20

cost:
  state: 1
  gate: 8

pbounds:
  a1:
    !!python/tuple [-2, 2]
  a2:
    !!python/tuple [-2, 2]
  a3:
    !!python/tuple [-2, 2]
  a4:
    !!python/tuple [-2, 2]
  a5:
    !!python/tuple [-2, 2]
  a6:
    !!python/tuple [-2, 2]