# Parameters for optimization routines
# Extra optimizations can be added as is done in "transfer:"

problem: three_q_yz

control:
  opt-1:
    iters: 210
    acq: 'ucb'
    kappa: 100
    kappa-decay: 0.8
    kappa-delay: 100

# Number of initialization iters for state and control optimizers
# These values must be the same for state and contorl to keep the testing fair
state-control-init: 30

cost:
  state: 1
  gate: 8

pbounds:
  a1:
    !!python/tuple [-3, 3]
  a2:
    !!python/tuple [-3, 3]
  a3:
    !!python/tuple [-3, 3]
  a4:
    !!python/tuple [-3, 3]
  a5:
    !!python/tuple [-3, 3]
  a6:
    !!python/tuple [-3, 3]

