# Parameters for optimization routines
# All parameters must be included
# Extra optimizations can be added as is done in "transfer:"
problem: two_q

input-states:
  - '00'

feedback: 0.3

state:
  opt-1:
    iters: 100
    acq: 'ucb'
    kappa: 15
    kappa-decay: 1
    kappa-delay: 0

transfer:
  opt-1:
    iters: 100
    acq: 'multi_ucb'
    kappa: 100
    kappa-decay: 1.0
    kappa-delay: 0
  opt-2:
    iters: 100
    acq: 'ei'
    kappa: 10
    kappa-decay: 1.0
    kappa-delay: 0

control:
  opt-1:
    iters: 225
    acq: 'ucb'
    kappa: 1
    kappa-decay: 0.8
    kappa-delay: 100

# Number of initialization iters for state and control optimizers
# These values must be the same for state and contorl to keep the testing fair
state-control-init: 20

# Initialisation for the transfer routine
transfer-init:
    iters: 5
    acq: 'ucb'
    kappa: 1
    xi: 0.0

cost:
  state: 1
  gate: 4

pbounds:
  a1:
    !!python/tuple [-2, 2]
  a2:
    !!python/tuple [-2, 2]
  a3:
    !!python/tuple [-2, 2]
  a4:
    !!python/tuple [-2, 2]
